# Generated by Django 6.1 on 2026-08-12 15:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleElement',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('lesson', 'Занятие'), ('activity', 'Мероприятие'), ('event', 'Событие'), ('supervision', 'Надзор'), ('gap', 'Пробел'), ('holiday', 'Каникулы'), ('announcement', 'Объявление')], max_length=20, verbose_name='Тип')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Краткое название')),
                ('long_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Цвет')),
                ('classification', models.CharField(choices=[('scheduled', 'Запланированное'), ('additional', 'Дополнительное'), ('substitution', 'Замена')], default='scheduled', max_length=20, verbose_name='Классификация')),
                ('temporal_expressions', models.JSONField(default=list, verbose_name='Временные выражения')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Элемент расписания',
                'verbose_name_plural': 'Элементы расписания',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('long_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Цвет')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ['short_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('long_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Цвет')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип курса',
                'verbose_name_plural': 'Типы курсов',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('long_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Цвет')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действительно с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действительно по')),
                ('course_number', models.CharField(blank=True, help_text='Например: 1, 2, 3, 4', max_length=10, verbose_name='Номер курса')),
                ('group_number', models.CharField(blank=True, help_text='Например: 22ИП2б', max_length=20, verbose_name='Номер группы')),
                ('faculty', models.CharField(blank=True, max_length=100, verbose_name='Факультет')),
                ('specialty', models.CharField(blank=True, max_length=200, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
                'ordering': ['course_number', 'short_name'],
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('long_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Цвет')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Тип группы',
                'verbose_name_plural': 'Типы групп',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('long_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Цвет')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200, verbose_name='Полное имя')),
                ('family_name', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('given_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['family_name', 'given_name'],
            },
        ),
        migrations.CreateModel(
            name='PersonRole',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('long_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Цвет')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('long_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Цвет')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='TimeFrame',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('long_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Цвет')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope_of_week', models.JSONField(default=list, help_text='["mon", "tue", ...]', verbose_name='Дни недели')),
                ('time_slots', models.JSONField(default=list, help_text='[{"shortLabel": "1", "startTime": "08:00", ...}]', verbose_name='Временные слоты')),
            ],
            options={
                'verbose_name': 'Временной каркас',
                'verbose_name_plural': 'Временные каркасы',
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('scheduleelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.scheduleelement')),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание')),
                ('long_description', models.TextField(blank=True, verbose_name='Полное описание')),
                ('priority', models.CharField(blank=True, choices=[('important', 'Важно'), ('alarm', 'Срочно')], max_length=20, verbose_name='Приоритет')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
            bases=('schedule.scheduleelement',),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('scheduleelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.scheduleelement')),
                ('holiday_type', models.CharField(choices=[('public', 'Государственный'), ('school', 'Школьные'), ('custom', 'Другие')], max_length=20, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Каникулы',
                'verbose_name_plural': 'Каникулы',
            },
            bases=('schedule.scheduleelement',),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('scheduleelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.scheduleelement')),
                ('lesson_type', models.CharField(blank=True, choices=[('lecture', 'Лекция'), ('practice', 'Практика'), ('lab', 'Лабораторная'), ('seminar', 'Семинар'), ('exam', 'Экзамен'), ('test', 'Зачет')], max_length=50, verbose_name='Тип занятия')),
                ('is_online', models.BooleanField(default=False, verbose_name='Онлайн')),
                ('zoom_link', models.URLField(blank=True, verbose_name='Ссылка на Zoom')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
                'ordering': ['temporal_expressions'],
            },
            bases=('schedule.scheduleelement',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('long_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Цвет')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_no', models.CharField(blank=True, max_length=20, verbose_name='Номер курса')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действительно с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действительно по')),
                ('course_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.coursetype', verbose_name='Тип курса')),
                ('groups', models.ManyToManyField(blank=True, related_name='courses', to='schedule.group', verbose_name='Группы')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['subject__short_name', 'short_name'],
            },
        ),
        migrations.AddField(
            model_name='group',
            name='group_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.grouptype', verbose_name='Тип группы'),
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='Действительно с')),
                ('valid_to', models.DateField(blank=True, null=True, verbose_name='Действительно по')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.group', verbose_name='Группа')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.person', verbose_name='Человек')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.personrole', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Участие в группе',
                'verbose_name_plural': 'Участия в группах',
                'unique_together': {('person', 'group')},
            },
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='groups', through='schedule.GroupMembership', to='schedule.person', verbose_name='Участники'),
        ),
        migrations.CreateModel(
            name='CourseAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.course', verbose_name='Курс')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.person', verbose_name='Человек')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.personrole', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Посещение курса',
                'verbose_name_plural': 'Посещения курсов',
                'unique_together': {('person', 'course')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='attendees',
            field=models.ManyToManyField(related_name='courses', through='schedule.CourseAttendance', to='schedule.person', verbose_name='Участники'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=100, primary_key=True, serialize=False)),
                ('short_name', models.CharField(max_length=100, verbose_name='Краткое название')),
                ('long_name', models.CharField(blank=True, max_length=200, verbose_name='Полное название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('color', models.CharField(default='#4A90D9', max_length=7, verbose_name='Цвет')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building_number', models.CharField(blank=True, help_text='Например: 1', max_length=10, verbose_name='Номер корпуса')),
                ('room_number', models.CharField(blank=True, help_text='Например: 237', max_length=20, verbose_name='Номер аудитории')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вместимость')),
                ('floor', models.PositiveIntegerField(blank=True, null=True, verbose_name='Этаж')),
                ('is_computer_class', models.BooleanField(default=False, verbose_name='Компьютерный класс')),
                ('is_lecture_hall', models.BooleanField(default=False, verbose_name='Лекционный зал')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='schedule.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Аудитория',
                'verbose_name_plural': 'Аудитории',
                'ordering': ['building_number', 'room_number'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='schedule.subject', verbose_name='Предмет'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('scheduleelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.scheduleelement')),
                ('attendees', models.ManyToManyField(blank=True, related_name='activities', to='schedule.person', verbose_name='Участники')),
                ('groups', models.ManyToManyField(blank=True, related_name='activities', to='schedule.group', verbose_name='Группы')),
                ('rooms', models.ManyToManyField(blank=True, related_name='activities', to='schedule.room', verbose_name='Аудитории')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
            bases=('schedule.scheduleelement',),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('scheduleelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.scheduleelement')),
                ('attendees', models.ManyToManyField(blank=True, related_name='events', to='schedule.person', verbose_name='Участники')),
                ('groups', models.ManyToManyField(blank=True, related_name='events', to='schedule.group', verbose_name='Группы')),
                ('rooms', models.ManyToManyField(blank=True, related_name='events', to='schedule.room', verbose_name='Аудитории')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
            bases=('schedule.scheduleelement',),
        ),
        migrations.CreateModel(
            name='Gap',
            fields=[
                ('scheduleelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='schedule.scheduleelement')),
                ('reasons', models.JSONField(default=list, help_text='Почему произошло изменение', verbose_name='Причины')),
                ('resolutions', models.JSONField(default=list, help_text='Что было сделано', verbose_name='Решения')),
                ('applies_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gaps', to='schedule.scheduleelement', verbose_name='Применяется к')),
            ],
            options={
                'verbose_name': 'Пробел',
                'verbose_name_plural': 'Пробелы',
                'ordering': ['-created_at'],
            },
            bases=('schedule.scheduleelement',),
        ),
        migrations.CreateModel(
            name='LessonAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.person', verbose_name='Человек')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.personrole', verbose_name='Роль')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.lesson', verbose_name='Занятие')),
            ],
            options={
                'verbose_name': 'Участие в занятии',
                'verbose_name_plural': 'Участия в занятиях',
                'unique_together': {('lesson', 'person')},
            },
        ),
        migrations.AddField(
            model_name='lesson',
            name='attendees',
            field=models.ManyToManyField(related_name='lessons', through='schedule.LessonAttendance', to='schedule.person', verbose_name='Участники'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='schedule.course', verbose_name='Курс'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='schedule.group', verbose_name='Группы'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='rooms',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='schedule.room', verbose_name='Аудитории'),
        ),
    ]
