# Generated by Django 6.1 on 2026-09-03 10:27

import schedule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='id',
            field=models.CharField(default=schedule.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(default=schedule.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='coursetype',
            name='id',
            field=models.CharField(default=schedule.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.CharField(default=schedule.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='id',
            field=models.CharField(default=schedule.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(default=schedule.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='personrole',
            name='id',
            field=models.CharField(default=schedule.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.CharField(default=schedule.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scheduleelement',
            name='id',
            field=models.CharField(default=schedule.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.CharField(default=schedule.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='timeframe',
            name='id',
            field=models.CharField(default=schedule.models.generate_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
